///////////////////////////////////////////////////////////
//  QDecoration.cs
//  Implementation of the Class QDecoration
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 12:40:39 AM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QDecoration : QTerm {

	public QDecoration(){

	}

	~QDecoration(){

	}

}//end QDecoration