///////////////////////////////////////////////////////////
//  QLemma.cs
//  Implementation of the Class QLemma
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 1:03:42 PM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QLemma : QTerm {

	public QLemma(){

	}

	~QLemma(){

	}

}//end QLemma