///////////////////////////////////////////////////////////
//  QSearchSegment.cs
//  Implementation of the Class QSearchSegment
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 12:40:40 AM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QSearchSegment {

	public int anchor;
	public QSearchFragment m_QSearchFragment;

	public QSearchSegment(){

	}

	~QSearchSegment(){

	}

}//end QSearchSegment