///////////////////////////////////////////////////////////
//  QSearchFragment.cs
//  Implementation of the Class QSearchFragment
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 12:40:40 AM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QSearchFragment {

	public QTerm m_QTerm;

	public QSearchFragment(){

	}

	~QSearchFragment(){

	}

}//end QSearchFragment