///////////////////////////////////////////////////////////
//  QTerm.cs
//  Implementation of the Class QTerm
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 12:40:40 AM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QTerm {

	public string text;

	public QTerm(){

	}

	~QTerm(){

	}

}//end QTerm