///////////////////////////////////////////////////////////
//  QWildcard.cs
//  Implementation of the Class QWildcard
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 1:03:50 PM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QWildcard : QTerm {

	public QWildcard(){

	}

	~QWildcard(){

	}

}//end QWildcard