///////////////////////////////////////////////////////////
//  QWord.cs
//  Implementation of the Class QWord
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 1:03:53 PM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QWord : QTerm {

	public QWord(){

	}

	~QWord(){

	}

}//end QWord