///////////////////////////////////////////////////////////
//  QDisplay.cs
//  Implementation of the Class QDisplay
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 12:40:39 AM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QDisplay : QImplicitCommand {

	public QShow m_QShow;

	public QDisplay(){

	}

	~QDisplay(){

	}

}//end QDisplay