///////////////////////////////////////////////////////////
//  QInvoke  QExec.cs
//  Implementation of the Class QInvoke / QExec
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 12:40:40 AM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QInvoke: QImplicitCommand {

	public QInvoke(){

	}

	~QInvoke(){

	}

}//end QInvoke