///////////////////////////////////////////////////////////
//  QSet  QClear.cs
//  Implementation of the Class QSet / QClear
//  Generated by Enterprise Architect
//  Created on:      18-Feb-2023 12:40:40 AM
//  Original author: Me
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



public class QSet: QImplicitCommand {

	public QSet(){

	}

	~QSet(){

	}

}//end QSet / QClear